# Form implementation generated from reading ui file '1.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets
from PyQt6.QtCore import Qt
from cris_mesh import MeshGenerator
from visual import *
from init_conditions import Init
import os
from report import report


class Ui_group(object):
    def setupUi(self, group):
        group.setObjectName("group")
        group.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(parent=group)
        self.centralwidget.setObjectName("centralwidget")

        # Main horizontal layout for 1:3 ratio
        self.main_layout = QtWidgets.QHBoxLayout(self.centralwidget)
        
        # Left side - Input box layout (1 part)
        self.left_layout = QtWidgets.QVBoxLayout()
        self.main_layout.addLayout(self.left_layout, 1)  # 1 part for input boxes

        # Right side - VisualizerWidget (3 parts)
        self.tabs = QTabWidget(self.centralwidget)  # Tạo QTabWidget với parent là centralwidget

        # Tạo các VisualizerWidget làm nội dung cho từng tab
        self.tab1 = VisualizerWidget(self.centralwidget)
        self.tab2 = VisualizerWidget(self.centralwidget)
 
        # Thêm tab1 và tab2 vào QTabWidget
        self.tabs.addTab(self.tab1, "Mesh")
        self.tabs.addTab(self.tab2, "Results")

        # Thêm QTabWidget vào layout chính
        self.main_layout.addWidget(self.tabs, 3)

        # Mesh box (generate section)
        self.mesh = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.mesh.setFlat(False)
        self.mesh.setCheckable(False)
        self.mesh.setObjectName("mesh")
        self.left_layout.addWidget(self.mesh)

        self.generate = QtWidgets.QPushButton(parent=self.mesh)
        self.generate.setGeometry(QtCore.QRect(20, 210, 271, 50))
        self.generate.setObjectName("generate")

        self.report = QtWidgets.QPushButton(parent=self.mesh)
        self.report.setGeometry(QtCore.QRect(300, 210, 70, 50))
        self.report.setObjectName("report")
        self.report.hide()

        self.type_of_naca = QtWidgets.QComboBox(parent=self.mesh)
        self.type_of_naca.setGeometry(QtCore.QRect(20, 50, 271, 31))
        self.type_of_naca.setEditable(True)
        self.type_of_naca.setObjectName("type_of_naca")
        self.type_of_naca.addItem("")
        self.type_of_naca.addItem("")

        self.type = QtWidgets.QComboBox(parent=self.mesh)
        self.type.setGeometry(QtCore.QRect(20, 130, 271, 31))
        self.type.setEditable(True)
        self.type.setCurrentText("")
        self.type.setDuplicatesEnabled(False)
        self.type.setObjectName("type")

        self.type_of_naca.currentTextChanged.connect(self.airfoil_type)

        self.label = QtWidgets.QLabel(parent=self.mesh)
        self.label.setGeometry(QtCore.QRect(30, 30, 81, 16))
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(parent=self.mesh)
        self.label_2.setGeometry(QtCore.QRect(30, 110, 71, 16))
        self.label_2.setObjectName("label_2")

        # Run box (hidden initially)
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.left_layout.addWidget(self.groupBox)
        self.groupBox.hide()  # Hide the groupBox initially

        self.mach = QtWidgets.QLineEdit(parent=self.groupBox)
        self.mach.setGeometry(QtCore.QRect(20, 90, 211, 22))
        self.mach.setText("")
        self.mach.setObjectName("mach")

        self.aoa = QtWidgets.QLineEdit(parent=self.groupBox)
        self.aoa.setGeometry(QtCore.QRect(20, 120, 211, 22))
        self.aoa.setText("")
        self.aoa.setObjectName("aoa")

        self.temp = QtWidgets.QLineEdit(parent=self.groupBox)
        self.temp.setGeometry(QtCore.QRect(20, 150, 211, 22))
        self.temp.setText("")
        self.temp.setObjectName("temp")

        self.pressure = QtWidgets.QLineEdit(parent=self.groupBox)
        self.pressure.setGeometry(QtCore.QRect(20, 180, 211, 22))
        self.pressure.setText("")
        self.pressure.setObjectName("pressure")

        self.solver = QtWidgets.QComboBox(parent=self.groupBox)
        self.solver.setGeometry(QtCore.QRect(20, 50, 211, 31))
        self.solver.setEditable(False)
        self.solver.setObjectName("solver")
        self.solver.addItem("")
        self.solver.addItem("")
        self.solver.addItem("")
        self.solver.addItem("")
        self.solver.addItem("")
        self.solver.addItem("")

        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 51, 20))
        self.label_3.setObjectName("label_3")

        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(240, 120, 49, 21))
        self.label_4.setObjectName("label_4")

        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(240, 150, 49, 21))
        self.label_5.setObjectName("label_5")

        self.label_6 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(240, 180, 49, 21))
        self.label_6.setObjectName("label_6")

        self.optimize = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.optimize.setFlat(False)
        self.optimize.setCheckable(False)
        self.optimize.setObjectName("mesh")
        self.left_layout.addWidget(self.optimize)

        self.run = QtWidgets.QPushButton(parent=self.groupBox)
        self.run.setGeometry(QtCore.QRect(20, 210, 271, 51))
        self.run.setObjectName("run")

        self.field = QtWidgets.QComboBox(parent=self.tab2)
        self.field.setEditable(False)
        self.field.setCurrentText("Pressure")
        self.field.setDuplicatesEnabled(False)
        self.field.setObjectName("field")
        self.field.addItems(["Pressure", "Temperature", "Velocity"])

        group.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(parent=group)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1902, 33))
        self.menubar.setObjectName("menubar")
        group.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(parent=group)
        self.statusbar.setObjectName("statusbar")
        group.setStatusBar(self.statusbar)

        group.showMaximized()

        self.retranslateUi(group)
        QtCore.QMetaObject.connectSlotsByName(group)

        # Connect the Generate button to show the Run box
        self.generate.clicked.connect(self.show_run_box)
        self.generate.clicked.connect(self.airfoil)
        self.report.clicked.connect(self.export_report)
        self.run.clicked.connect(self.sim)
        self.field.activated.connect(self.show)
    def show_run_box(self):
        self.groupBox.show()  # Show the Run box after hitting generate
        self.report.show()
    
    def export_report(self):
        self.baocao=report.doc(self)

    def retranslateUi(self, group):
        _translate = QtCore.QCoreApplication.translate
        group.setWindowTitle(_translate("group", "Airfoil CFD Simulation"))

        self.mesh.setTitle(_translate("group", "Mesh"))
        self.generate.setText(_translate("group", "GENERATE"))
        self.report.setText(_translate("group", "REPORT"))
        self.type_of_naca.setItemText(0, _translate("group", "NACA 4 digit"))
        self.type_of_naca.setItemText(1, _translate("group", "NACA 5 digit"))
        self.type_of_naca.setItemText(2, _translate("group", "Others"))
        self.label.setText(_translate("group", "Select group"))
        self.label_2.setText(_translate("group", "Select airfoil"))

        self.optimize.setTitle(_translate("group", "Optimization"))

        self.groupBox.setTitle(_translate("group", "Initial Conditions"))
        self.mach.setPlaceholderText(_translate("group", "Mach number"))
        self.aoa.setPlaceholderText(_translate("group", "AOA"))
        self.temp.setPlaceholderText(_translate("group", "Temperature"))
        self.pressure.setPlaceholderText(_translate("group", "Pressure"))

        self.solver.setItemText(0, _translate("group", "EULER"))
        self.solver.setItemText(1, _translate("group", "NAVIER-STOKES"))
        self.solver.setItemText(2, _translate("group", "WAVE EQUATION"))
        self.solver.setItemText(3, _translate("group", "HEAT EQUATION"))
        self.solver.setItemText(4, _translate("group", "FEM ELASTICITY"))
        self.solver.setItemText(5, _translate("group", "POISSON EQUATION"))

        self.label_3.setText(_translate("group", "Solver"))
        self.label_4.setText(_translate("group", "(Degree)"))
        self.label_5.setText(_translate("group", "(K)"))
        self.label_6.setText(_translate("group", "(Pa)"))
        self.run.setText(_translate("group", "RUN"))

    def inform(self):
        msg=QtWidgets.QMessageBox()
        msg.setWindowFlags(msg.windowFlags() | Qt.WindowType.WindowStaysOnTopHint)
        msg.setInformativeText('Success!')
        msg.exec()
        
    def airfoil_type(self, group): #select airfoil type 
        if group == "NACA 4 digit":
            self.type.clear()
            self.type.addItems(["NACA 0012", "NACA 2412"])
        elif group == "NACA 5 digit":
            self.type.clear()
            self.type.addItems(["NACA 63206", "NACA 63209"])

    def airfoil(self): #generate mesh and post-processing mesh
        self.gen=MeshGenerator(group=self.type_of_naca.currentText(),type=self.type.currentText())
        self.gen.mesh_generated.connect(self.on_mesh_generated)
        self.gen.start()
        self.inform
    def on_mesh_generated(self, data):
        self.data=data
        self.tab1.show_mesh(data=self.data["mesh_vtk"])

    def sim(self): #run simulation
        code=MeshGenerator.naca_code(group=self.type_of_naca.currentText(),type=self.type.currentText())
        mesh_path = os.path.join(f'NACA_{code}', f"mesh_airfoil_{code}.su2" ) 
        self.run=Init(solver=self.solver.currentText(),mach=self.mach.text(),aoa=self.aoa.text(),temperature=self.temp.text(),pressure=self.pressure.text(), mesh_path=mesh_path, folder_name=f'NACA_{code}')
        self.run.start()

    def show(self):
        code=MeshGenerator.naca_code(group=self.type_of_naca.currentText(),type=self.type.currentText())
        self.tab2.show(data=os.path.join(f'NACA_{code}', 'flow.vtu' ),field=self.field.currentText())
    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    group = QtWidgets.QMainWindow()
    ui = Ui_group()
    ui.setupUi(group)
    group.show()
    sys.exit(app.exec())
